export const TOGGLE_VIEW = 'TOGGLE_VIEW';
export const LOAD_TABLE = 'LOAD_TABLE';
export const LOAD_TABLE_ERROR = 'LOAD_TABLE_ERROR';
export const UPDATE_TABLE_ROW = 'UPDATE_TABLE_ROW';
export const ADD_TABLE_ROW = 'ADD_TABLE_ROW';
export const DELETE_TABLE_ROW = 'DELETE_TABLE_ROW';

//TICKETS CONSTANTS
export const TOOGLE_TICKETS = 'TOOGLE_TICKETS';
export const CREATE_TICKET = 'CREATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';

//FLIGHT CONSTANTS
export const TOOGLE_FLIGHTS = 'TOOGLE_FLIGHTS';
export const CREATE_FLIGHT = 'CREATE_FLIGHT';
export const DELETE_FLIGHT = 'DELETE_FLIGHT';
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';

//PASSANGERS CONSTANTS
export const TOOGLE_PASSANGERS = 'TOOGLE_PASSANGERS';
export const CREATE_PASSANGERS = 'CREATE_PASSANGERS';
export const DELETE_PASSANGERS = 'DELETE_PASSANGERS';
export const UPDATE_PASSANGERS = 'UPDATE_PASSANGERS';

export const views = {
    Home: 'Home',
    Flights: 'Flights',
    Tickets: 'Tickets',
    PASSANGERS: 'Passangers'
}